version: '2'

services:
    ms:
        image: gebart/leshan
        ports:
        - 8081:8080
    weather:
        build:
           context: .
        environment:
        - FILE=${WEATHER}
        #mem_limit: 4m
        depends_on:
        - ms
    presence:
        build:
           context: .
        environment:
        - FILE=${PRESENCE}
        #mem_limit: 4m
        depends_on:
        - ms
    radiator:
       build:
         context: .
       environment:
       - FILE=${RADIATOR}
       #mem_limit: 4m
       depends_on:
       - ms
    light:
       build:
         context: .
       environment:
       - FILE=${LIGHT}
       #mem_limit: 4m
       depends_on:
       - ms
