version: '2'

services:
    ms:
        image: corfr/leshan
        ports:
        - 8080:8080/tcp
        - 5683:5683/udp
        depends_on:
        - bss
    bss:
        image: corfr/leshan
        ports:
        - 8081:8080
        command: bootstrap
    weather:
        image: alliasd/eliot
        environment:
        - FILE=${WEATHER}
        depends_on:
        - bss
        - ms
    presence:
        image: alliasd/eliot
        environment:
        - FILE=${PRESENCE}
        depends_on:
        - bss
        - ms
    radiator:
       image: alliasd/eliot
       environment:
       - FILE=${RADIATOR}
       depends_on:
       - bss
       - ms
    light:
       image: alliasd/eliot
       environment:
       - FILE=${LIGHT}
       depends_on:
       - bss
       - ms
