version: '2'

services:
    ms:
        image: corfr/leshan
        ports:
        - 8080:8080
        - 5683:5683
    weather:
        image: alliasd/eliot
        environment:
        - FILE=${WEATHER}
        #mem_limit: 4m
        depends_on:
        - ms
    presence:
        image: alliasd/eliot
        environment:
        - FILE=${PRESENCE}
        #mem_limit: 4m
        depends_on:
        - ms
    radiator:
       image: alliasd/eliot
       environment:
       - FILE=${RADIATOR}
       #mem_limit: 4m
       depends_on:
       - ms
    light:
       image: alliasd/eliot
       environment:
       - FILE=${LIGHT}
       #mem_limit: 4m
       depends_on:
       - ms
